"""tinydata public API."""

from __future__ import annotations

from typing import Any, Iterable, Optional, Sequence

import pandas as pd

from .client import TinyClient
from .config import configure as _configure
from .config import get_config, reset_config as _reset_config
from .datasets import (
    bond_basic_ext,
    cbond_daily,
    fina_balancesheet,
    fina_cashflow,
    fina_disclosure,
    fina_express,
    fina_forecast,
    fina_income,
    fina_indicator,
    fina_mainbz,
    fina_mainbz_area,
    fina_mainbz_industry,
    fina_mainbz_product,
    fund_abs_holding_detail,
    fund_adjusted_nav,
    fund_asset_alloc,
    fund_balance_sheet,
    fund_benchmark,
    fund_basic,
    fund_basic_ext,
    fund_bond_alloc,
    fund_bond_holding,
    fund_bond_holding_detail,
    fund_broker_seat,
    fund_buy_sell,
    fund_cbond_holding_detail,
    fund_classification_info,
    fund_classification_member,
    fund_dividend,
    fund_etf_constituent,
    fund_etf_sub_redemption,
    fund_fee,
    fund_financial_quarterly_ext,
    fund_fof_holding_detail,
    fund_holder_structure,
    fund_income_statement,
    fund_industry_alloc,
    fund_manager,
    fund_manager_ext,
    fund_daily,
    fund_namechange,
    fund_nav,
    fund_nav_benchmark_return,
    fund_share,
    fund_split,
    fund_stock_holding,
    fund_stock_holding_detail,
    fund_top_holder,
    future_basic_ext,
    future_daily,
    future_product_mapping_ext,
    get_dataset_info,
    hk_daily,
    index_basic_ext,
    index_daily,
    index_member_snapshot,
    index_member_versioned,
    index_weight,
    list_datasets,
    market_calendar_multi,
    option_daily,
    option_basic_daily_ext,
    query_market_panel,
    stock_blocktrade,
    stock_basic_ext,
    stock_classification_info,
    stock_controller,
    stock_delist_solution,
    stock_daily,
    stock_dividend,
    stock_fina_pit_ext,
    stock_foreign_holding,
    stock_holdernumber,
    stock_holder_change_ext,
    stock_hsgt_daily,
    stock_hsgt_hold,
    stock_hsgt_short_balance,
    stock_hsgt_top10,
    stock_industry_versioned,
    stock_ipo,
    stock_lending_balance,
    stock_lending_summary,
    stock_lending_trade,
    stock_margin,
    stock_margindetail,
    stock_margin_collateral,
    stock_monthly,
    stock_namechange,
    stock_nonrecurring,
    stock_officer_hold_change,
    stock_pledge_balance,
    stock_pledge_detail,
    stock_pledge_rate,
    stock_pledge_summary,
    stock_public_trade_info,
    stock_repurchase_ext,
    stock_sharefloat,
    stock_suspend,
    stock_top10_float_holder,
    stock_top10_holder,
    stock_trade_time,
    stock_unlock_schedule,
    stock_weekly,
    trade_calendar,
)
from .errors import (
    TinyDataAuthError,
    TinyDataCodePoolError,
    TinyDataConfigError,
    TinyDataDependencyError,
    TinyDataError,
    TinyDataParameterError,
    TinyDataQueryError,
    TinyDataRateLimitError,
    TinyDataTimeoutError,
)
from .infotable import InfoTableOptions, query_infotable as _query_infotable
from .universe import (
    bond_codes,
    fof_fund_codes,
    fund_codes,
    fund_market_codes,
    future_codes,
    index_codes,
    market_codes,
    option_codes,
    stock_codes,
)

__version__ = "1.2.1"

_DEFAULT_CLIENT: Optional[TinyClient] = None


def get_client() -> TinyClient:
    global _DEFAULT_CLIENT
    if _DEFAULT_CLIENT is None:
        _DEFAULT_CLIENT = TinyClient(get_config())
    return _DEFAULT_CLIENT


def configure(
    user: Optional[str] = None,
    password: Optional[str] = None,
    host: Optional[str] = None,
    port: Optional[int] = None,
    ini_path: Optional[str] = None,
    opi_url: Optional[str] = None,
    opi_auth_mode: Optional[str] = None,
    session_key: Optional[str] = None,
    session_password: Optional[str] = None,
    service: Optional[str] = None,
    json_encode: Optional[str] = None,
    run_func_name: Optional[str] = None,
    query_func_name: Optional[str] = None,
    cache_dir: Any = None,
    request_interval: Optional[float] = None,
    timeout_ms: Optional[int] = None,
):
    """Configure tinydata and reset the default Tinysoft client."""

    global _DEFAULT_CLIENT
    cfg = _configure(
        user=user,
        password=password,
        host=host,
        port=port,
        ini_path=ini_path,
        opi_url=opi_url,
        opi_auth_mode=opi_auth_mode,
        session_key=session_key,
        session_password=session_password,
        service=service,
        json_encode=json_encode,
        run_func_name=run_func_name,
        query_func_name=query_func_name,
        cache_dir=cache_dir,
        request_interval=request_interval,
        timeout_ms=timeout_ms,
    )
    _DEFAULT_CLIENT = TinyClient(cfg)
    return cfg


def configure_client(**kwargs: Any) -> TinyClient:
    """Configure tinydata and return a fresh default Tinysoft client."""

    configure(**kwargs)
    assert _DEFAULT_CLIENT is not None
    return _DEFAULT_CLIENT


def reset_config() -> None:
    """Clear explicit configuration and discard the default client."""

    global _DEFAULT_CLIENT
    _reset_config()
    _DEFAULT_CLIENT = None


def query_infotable(
    table_id: int,
    codes: Optional[Iterable[Any]] = None,
    start_date: Any = None,
    end_date: Any = None,
    date_field: Optional[str] = None,
    fields: Optional[Sequence[str]] = None,
    as_of_date: Any = None,
    report_mode: Optional[int] = None,
    allow_full_table: bool = False,
    code_batch_size: Optional[int] = None,
    max_workers: Optional[int] = None,
    progress: Optional[bool] = None,
) -> pd.DataFrame:
    return _query_infotable(
        get_client(),
        table_id,
        codes=codes,
        start_date=start_date,
        end_date=end_date,
        date_field=date_field,
        fields=fields,
        as_of_date=as_of_date,
        report_mode=report_mode,
        allow_full_table=allow_full_table,
        options=InfoTableOptions(
            code_batch_size=code_batch_size or 100,
            max_workers=max_workers,
            progress=progress,
        ),
    )


def query_market(
    symbol: str,
    start_time: str,
    end_time: str,
    cycle: str = "1分钟线",
    fields: Optional[Iterable[Any]] = None,
    adjust: Any = None,
    adjust_date: Any = None,
) -> pd.DataFrame:
    return get_client().query(
        stock=symbol,
        cycle=cycle,
        begin_time=start_time,
        end_time=end_time,
        fields=fields,
        adjust=adjust,
        adjust_date=adjust_date,
    )


__all__ = [
    "TinyClient",
    "TinyDataAuthError",
    "TinyDataCodePoolError",
    "TinyDataConfigError",
    "TinyDataDependencyError",
    "TinyDataError",
    "TinyDataParameterError",
    "TinyDataQueryError",
    "TinyDataRateLimitError",
    "TinyDataTimeoutError",
    "bond_codes",
    "bond_basic_ext",
    "cbond_daily",
    "configure",
    "configure_client",
    "fof_fund_codes",
    "fina_balancesheet",
    "fina_cashflow",
    "fina_disclosure",
    "fina_express",
    "fina_forecast",
    "fina_income",
    "fina_indicator",
    "fina_mainbz",
    "fina_mainbz_area",
    "fina_mainbz_industry",
    "fina_mainbz_product",
    "fund_abs_holding_detail",
    "fund_adjusted_nav",
    "fund_asset_alloc",
    "fund_balance_sheet",
    "fund_benchmark",
    "fund_basic",
    "fund_basic_ext",
    "fund_daily",
    "fund_bond_alloc",
    "fund_bond_holding",
    "fund_bond_holding_detail",
    "fund_broker_seat",
    "fund_buy_sell",
    "fund_cbond_holding_detail",
    "fund_classification_info",
    "fund_classification_member",
    "fund_codes",
    "fund_dividend",
    "fund_etf_constituent",
    "fund_etf_sub_redemption",
    "fund_fee",
    "fund_financial_quarterly_ext",
    "fund_fof_holding_detail",
    "fund_holder_structure",
    "fund_income_statement",
    "fund_industry_alloc",
    "fund_manager",
    "fund_manager_ext",
    "fund_market_codes",
    "fund_namechange",
    "fund_nav",
    "fund_nav_benchmark_return",
    "fund_share",
    "fund_split",
    "fund_stock_holding",
    "fund_stock_holding_detail",
    "fund_top_holder",
    "future_codes",
    "future_basic_ext",
    "future_daily",
    "future_product_mapping_ext",
    "get_config",
    "get_dataset_info",
    "hk_daily",
    "index_basic_ext",
    "index_codes",
    "index_daily",
    "index_member_snapshot",
    "index_member_versioned",
    "index_weight",
    "list_datasets",
    "market_calendar_multi",
    "market_codes",
    "option_codes",
    "option_daily",
    "option_basic_daily_ext",
    "query_infotable",
    "query_market",
    "query_market_panel",
    "reset_config",
    "stock_blocktrade",
    "stock_basic_ext",
    "stock_classification_info",
    "stock_controller",
    "stock_delist_solution",
    "stock_codes",
    "stock_daily",
    "stock_dividend",
    "stock_fina_pit_ext",
    "stock_foreign_holding",
    "stock_holdernumber",
    "stock_holder_change_ext",
    "stock_hsgt_daily",
    "stock_hsgt_hold",
    "stock_hsgt_short_balance",
    "stock_hsgt_top10",
    "stock_industry_versioned",
    "stock_ipo",
    "stock_lending_balance",
    "stock_lending_summary",
    "stock_lending_trade",
    "stock_margin",
    "stock_margindetail",
    "stock_margin_collateral",
    "stock_monthly",
    "stock_namechange",
    "stock_nonrecurring",
    "stock_officer_hold_change",
    "stock_pledge_balance",
    "stock_pledge_detail",
    "stock_pledge_rate",
    "stock_pledge_summary",
    "stock_public_trade_info",
    "stock_repurchase_ext",
    "stock_sharefloat",
    "stock_suspend",
    "stock_top10_float_holder",
    "stock_top10_holder",
    "stock_trade_time",
    "stock_unlock_schedule",
    "stock_weekly",
    "trade_calendar",
    "__version__",
]
